KevinDik/digital_burger

- digital_burger/assets/js/index.html
#24 Definindo layout base em um html externo para ser transpilado para o JS
> definindo layout base

- digital_burger/assets/css/style.css
- digital_burger/index.html
#3 Criando estilo inicial do footer
> style: Criando layout base do footer

- digital_burger/assets/css/reset.css
- digital_burger/assets/css/style.css
- digital_burger/index.html
#11 Criado variaveis das fontes padroes
> Setado as fontes padroes e definido nos produtos as cores e fontes

- digital_burger/assets/css/style.css
- digital_burger/assets/js/GoLangBurger.js
- digital_burger/assets/js/JavaBurger.js
- digital_burger/assets/js/PythonBurger.js
- digital_burger/assets/js/TypeScriptBurger.js
- digital_burger/index.html
#30 Criado Js para gerar os burges
> feat: Criando componentes dos hamburgers

- README.md
> fix atualizando README

- digital_burger/assets/css/style.css
- digital_burger/assets/js/footer.js
- digital_burger/assets/js/products.js
- digital_burger/index.html
#3 Arquivo JS do footer criado. Criar o mesmo footer so sera necessario importar o JS footer.js e criar a TAG footer com a classe .footer
> feat: Criado componente para gerar o footer via JS

- digital_burger/assets/css/style.css
#24 Adicionando hover nos cards
> style: Realizado melhoria nos cards com hover

- digital_burger/assets/css/style.css
- digital_burger/assets/js/products.js
#24 ajustando CSS dos produtos
> style: ajustando os produtos

- digital_burger/assets/css/reset.css
> fix: ajustando fontes do footer

- digital_burger/assets/pages/quemSomos.html
> alterado as informações da tag P

- digital_burger/assets/css/cat-prods.css
- digital_burger/assets/pages/cad-categoria.html
- digital_burger/assets/pages/cad-produtos.html
> feat: Criado tela de admin

- digital_burger/assets/css/reset.css
> criando linha before do footer

- assets/js/burgers.js
> corrindo icones de glutem

- assets/css/quemSomos.css
#59 Feito tela responsiva nas medidas de 768px e 400px
> feito responsividade do quemSomo

- assets/css/style.css
- index.html
> corrindo bug do layout com telas diferentes

- assets/css/login.css
Corrigindo bug do botao de login
> adicionado o cursor pointer no login

- assets/css/style.css
Alterando o espaçamento das categorias
> corrigindo alinhamento das categorias

- assets/css/style.css
- assets/js/login.js
> fix: Corrigindo o bug do login

- _app/src/assets/components/layout/Categories.css
- _app/src/assets/components/layout/Categories.tsx
- _app/src/assets/components/pages/Cardapio.tsx
> feat: criado componente de categorias

- _app/src/assets/components/layout/Footer.css
- _app/src/assets/components/layout/Footer.tsx
> style: Trabalhando em cima do estilo do footer
